<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!doctype html>
<html lang="en">
<head>
    <title><b> JSP TestPage Revenue </b></title>
    <style>
        body {
            background-color: #ffffe6;
        }

        p {
            color: grey;
            font-family: cursive;
            font-size: 90%;
        }
    </style>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#buyDatePicker").datepicker({dateFormat: "yy-mm-dd",
                changeMonth: true,
                changeYear: true,
            }).val()
            $("#sellDatePicker").datepicker({dateFormat: "yy-mm-dd",
                changeMonth: true,
                changeYear: true}).val()
        });
    </script>


</html>


</head>
<body>
<p style={font-size:120%}><b>JSP TestPage</b></p>

<p>INFO: Generated by TestServlet.java: </p>
<p>If you see this page it means your basic local server configuration</br>is set properly and application is able to
    use imported JAR dependency</br>from DMM_Finance Project Sprint_1</p>

<form method="post" action="revenue" >
    <p>
        Enter data (for example funds: "AIP001", "CHF" capital: "12000", buy date "2009-09-10", sell date "2017-04-02"):
    </p>
    <p>investment name: <input type="text" name="investmenName" style="width:60px" id ="inputForm"/></p>
    <p>capital <input type="text" name="capital" style="width:100px"/></p>
    <p>buy date <input type="text" id="buyDatePicker" name="buyDate" readonly='true' style="width:85px"/></p>
    <p>sell date <input type="text" id="sellDatePicker" name="sellDate" readonly='true' style="width:85px"/></p>

    <p>
        <button type="submit">Send!</button>
    </p>

</form>


<p><b> Analysis result: </b></p>

<p><b> input data: </b></p>
<p><b>Investment name: </b> <b>${i_investmentName}</b></p>
<p>invested capital: <b>${i_investedCapital}</b></p>
<p>buy date: <b>${i_buyDate}</b></p>
<p>sell date: <b>${i_sellDate}</b></p>

<p><b> output data: </b></p>
<p>finally processed data: </p>
<p>buy date: <b>${f_buyDate}</b></p>
<p>sell date: <b>${f_sellDate}</b></p>

<p><b> output data: </b></p>
<p>Capital Revenue: <b>${r_capitalRevenue}</b></p>
<p>Capital Revenue Delta: <b>${r_capitalRevenueDelta}</b></p>

<p> *** End of content *** </p>

</body>
</html>