<%@ taglib prefix="utils" tagdir="/WEB-INF/tags" %>


<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title><b> JSP TestPage </b></title>
    <style>
        body {background-color: #ffffe6;}
        p    {color: grey; font-family:cursive; font-size: 90%;}
    </style>
</head>
<body>
<p style={font-size:120%}><b>JSP TestPage</b></p>

<p>INFO: Generated by TestServlet.java: </p>
<p>If you see this page it means your basic local server configuration</br>is set properly and application is able to use imported JAR dependency</br>from DMM_Finance Project Sprint_1</p>

<form method="post" action="test">
    <p>
        Enter Investment name (for example funds: "AIP001", "AGI001", currencies: "CHF", "AUD", etc.):
    </p>
    <p>
    <input type="text" name="name" style="width:80px" />
        <button type="submit">Send!</button>
    </p>
</form>

<p><b> Investment statistics: </b>  </p>

<p><b>name: </b>  <b>${investmentName}</b> </p>

<p>Brief quotation info: </p>
<p>first date: <b>${firstQuotationDate}</b> value: <b>${firstQuotationValue}</b> </p>

<p>last date: <b>${lastQuotationDate}</b> value: <b>${lastQuotationValue}</b> </p>

<p>max rise</p>
<p>date: <b>${maxDeltaPlusDate}</b> value: <b>${maxDeltaPlusValue}</b>change: <b>${maxDeltaPlusDelta}</b>[%]</p>

<p>max fall</p>
<p>date <b>${maxDeltaMinusDate}</b> value: <b>${maxDeltaMinusValue}</b>change: <b>${maxDeltaMinusDelta}</b>[%]</p>

<p>max nominal value</p>
<p>date <b>${maxValueQuotationDate}</b> vlaue: <b>${maxValueQuotationValue}</b> change:  <b>${maxValueQuotationDelta}</b>[%]</p>

<p>min nominal vlaue [%]</p>
<p>date <b>${minValueQuotationDate}</b> value: <b>${minValueQuotationValue}</b> change: <b>${minValueQuotationDelta}</b>[%] </p>

<p>actual vale: <b>${lastQuotationValue}</b></p>

<p> *** End of content *** </p>


<utils:test message="${investment}" />


</body>
</html>
