<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title><b> JSP TestPage Revenue </b></title>
    <style>
        body {background-color: #ffffe6;}
        p    {color: grey; font-family:cursive; font-size: 90%;}
    </style>
</head>
<body>
<p style={font-size:120%}><b>JSP TestPage</b></p>

<p>INFO: Generated by TestServlet.java: </p>
<p>If you see this page it means your basic local server configuration</br>is set properly and application is able to use imported JAR dependency</br>from DMM_Finance Project Sprint_1</p>

<form method="post" action="revenue">
    <p>
        Enter data (for example funds: "AIP001", "CHF" capital: "12000", buy date "20090910", sell date "20170402"):
    </p>
    <p>investment name:  <input type="text" name="investmenName" style="width:300px" /></p>
    <p>capital <input type="text" name="capital" style="width:300px" /></p>
    <p>buy date <input type="text" name="buyDate" style="width:300px" /></p>
    <p>sell date <input type="text" name="sellDate" style="width:300px" /></p>
    <p>
        <button type="submit">Send!</button>
    </p>
</form>


<p><b> Analysis result: </b>  </p>

<p><b> input data: </b>  </p>
<p><b>Investment name: </b>  <b>${i_investmentName}</b> </p>
<p>invested capital: <b>${i_investedCapital}</b></p>
<p>buy date: <b>${i_buyDate}</b></p>
<p>sell date: <b>${i_sellDate}</b></p>

<p><b> output data: </b>  </p>
<p>finally processed data: </p>
<p>buy date: <b>${f_buyDate}</b></p>
<p>sell date: <b>${f_sellDate}</b></p>

<p><b> output data: </b>  </p>
p>Capital Revenue: <b>${r_capitalRevenue}</b></p>
p>Capital Revenue Delta: <b>${r_capitalRevenueDelta}</b></p>

<p> *** End of content *** </p>

</body>
</html>